// ─── 국가 데이터 ───
export type Country = { term: string; flag: string; name: string; continent: string };
export const CONTINENT_ORDER = ['아시아', '유럽', '북아메리카', '남아메리카', '아프리카', '오세아니아'];
export const COUNTRIES: Country[] = [
  { term: 'kr 대한민국 korea', flag: '🇰🇷', name: '대한민국', continent: '아시아' },
  { term: 'jp 일본 japan', flag: '🇯🇵', name: '일본', continent: '아시아' },
  { term: 'cn 중국 china', flag: '🇨🇳', name: '중국', continent: '아시아' },
  { term: 'tw 대만 taiwan', flag: '🇹🇼', name: '대만', continent: '아시아' },
  { term: 'hk 홍콩 hong kong', flag: '🇭🇰', name: '홍콩', continent: '아시아' },
  { term: 'mo 마카오 macau', flag: '🇲🇴', name: '마카오', continent: '아시아' },
  { term: 'th 태국 thailand', flag: '🇹🇭', name: '태국', continent: '아시아' },
  { term: 'vn 베트남 vietnam', flag: '🇻🇳', name: '베트남', continent: '아시아' },
  { term: 'ph 필리핀 philippines', flag: '🇵🇭', name: '필리핀', continent: '아시아' },
  { term: 'id 인도네시아 indonesia', flag: '🇮🇩', name: '인도네시아', continent: '아시아' },
  { term: 'my 말레이시아 malaysia', flag: '🇲🇾', name: '말레이시아', continent: '아시아' },
  { term: 'sg 싱가포르 singapore', flag: '🇸🇬', name: '싱가포르', continent: '아시아' },
  { term: 'kh 캄보디아 cambodia', flag: '🇰🇭', name: '캄보디아', continent: '아시아' },
  { term: 'la 라오스 laos', flag: '🇱🇦', name: '라오스', continent: '아시아' },
  { term: 'mm 미얀마 myanmar burma', flag: '🇲🇲', name: '미얀마', continent: '아시아' },
  { term: 'bn 브루나이 brunei', flag: '🇧🇳', name: '브루나이', continent: '아시아' },
  { term: 'tl 동티모르 east timor timor-leste', flag: '🇹🇱', name: '동티모르', continent: '아시아' },
  { term: 'in 인도 india', flag: '🇮🇳', name: '인도', continent: '아시아' },
  { term: 'lk 스리랑카 sri lanka', flag: '🇱🇰', name: '스리랑카', continent: '아시아' },
  { term: 'np 네팔 nepal', flag: '🇳🇵', name: '네팔', continent: '아시아' },
  { term: 'bt 부탄 bhutan', flag: '🇧🇹', name: '부탄', continent: '아시아' },
  { term: 'pk 파키스탄 pakistan', flag: '🇵🇰', name: '파키스탄', continent: '아시아' },
  { term: 'bd 방글라데시 bangladesh', flag: '🇧🇩', name: '방글라데시', continent: '아시아' },
  { term: 'mv 몰디브 maldives', flag: '🇲🇻', name: '몰디브', continent: '아시아' },
  { term: 'mn 몽골 mongolia', flag: '🇲🇳', name: '몽골', continent: '아시아' },
  { term: 'kz 카자흐스탄 kazakhstan', flag: '🇰🇿', name: '카자흐스탄', continent: '아시아' },
  { term: 'uz 우즈베키스탄 uzbekistan', flag: '🇺🇿', name: '우즈베키스탄', continent: '아시아' },
  { term: 'tm 투르크메니스탄 turkmenistan', flag: '🇹🇲', name: '투르크메니스탄', continent: '아시아' },
  { term: 'tj 타지키스탄 tajikistan', flag: '🇹🇯', name: '타지키스탄', continent: '아시아' },
  { term: 'kg 키르기스스탄 kyrgyzstan', flag: '🇰🇬', name: '키르기스스탄', continent: '아시아' },
  { term: 'af 아프가니스탄 afghanistan', flag: '🇦🇫', name: '아프가니스탄', continent: '아시아' },
  { term: 'ir 이란 iran', flag: '🇮🇷', name: '이란', continent: '아시아' },
  { term: 'iq 이라크 iraq', flag: '🇮🇶', name: '이라크', continent: '아시아' },
  { term: 'sa 사우디아라비아 saudi arabia', flag: '🇸🇦', name: '사우디아라비아', continent: '아시아' },
  { term: 'ae 아랍에미리트 uae united arab emirates', flag: '🇦🇪', name: '아랍에미리트', continent: '아시아' },
  { term: 'kw 쿠웨이트 kuwait', flag: '🇰🇼', name: '쿠웨이트', continent: '아시아' },
  { term: 'bh 바레인 bahrain', flag: '🇧🇭', name: '바레인', continent: '아시아' },
  { term: 'qa 카타르 qatar', flag: '🇶🇦', name: '카타르', continent: '아시아' },
  { term: 'om 오만 oman', flag: '🇴🇲', name: '오만', continent: '아시아' },
  { term: 'ye 예멘 yemen', flag: '🇾🇪', name: '예멘', continent: '아시아' },
  { term: 'jo 요르단 jordan', flag: '🇯🇴', name: '요르단', continent: '아시아' },
  { term: 'il 이스라엘 israel', flag: '🇮🇱', name: '이스라엘', continent: '아시아' },
  { term: 'ps 팔레스타인 palestine', flag: '🇵🇸', name: '팔레스타인', continent: '아시아' },
  { term: 'lb 레바논 lebanon', flag: '🇱🇧', name: '레바논', continent: '아시아' },
  { term: 'sy 시리아 syria', flag: '🇸🇾', name: '시리아', continent: '아시아' },
  { term: 'tr 튀르키예 turkey turkiye', flag: '🇹🇷', name: '튀르키예', continent: '아시아' },
  { term: 'cy 키프로스 cyprus', flag: '🇨🇾', name: '키프로스', continent: '아시아' },
  { term: 'am 아르메니아 armenia', flag: '🇦🇲', name: '아르메니아', continent: '아시아' },
  { term: 'az 아제르바이잔 azerbaijan', flag: '🇦🇿', name: '아제르바이잔', continent: '아시아' },
  { term: 'ge 조지아 georgia', flag: '🇬🇪', name: '조지아', continent: '아시아' },
  { term: 'gb 영국 uk united kingdom', flag: '🇬🇧', name: '영국', continent: '유럽' },
  { term: 'fr 프랑스 france', flag: '🇫🇷', name: '프랑스', continent: '유럽' },
  { term: 'de 독일 germany', flag: '🇩🇪', name: '독일', continent: '유럽' },
  { term: 'it 이탈리아 italy', flag: '🇮🇹', name: '이탈리아', continent: '유럽' },
  { term: 'es 스페인 spain', flag: '🇪🇸', name: '스페인', continent: '유럽' },
  { term: 'pt 포르투갈 portugal', flag: '🇵🇹', name: '포르투갈', continent: '유럽' },
  { term: 'nl 네덜란드 netherlands', flag: '🇳🇱', name: '네덜란드', continent: '유럽' },
  { term: 'be 벨기에 belgium', flag: '🇧🇪', name: '벨기에', continent: '유럽' },
  { term: 'ch 스위스 switzerland', flag: '🇨🇭', name: '스위스', continent: '유럽' },
  { term: 'at 오스트리아 austria', flag: '🇦🇹', name: '오스트리아', continent: '유럽' },
  { term: 'se 스웨덴 sweden', flag: '🇸🇪', name: '스웨덴', continent: '유럽' },
  { term: 'no 노르웨이 norway', flag: '🇳🇴', name: '노르웨이', continent: '유럽' },
  { term: 'dk 덴마크 denmark', flag: '🇩🇰', name: '덴마크', continent: '유럽' },
  { term: 'fi 핀란드 finland', flag: '🇫🇮', name: '핀란드', continent: '유럽' },
  { term: 'is 아이슬란드 iceland', flag: '🇮🇸', name: '아이슬란드', continent: '유럽' },
  { term: 'ie 아일랜드 ireland', flag: '🇮🇪', name: '아일랜드', continent: '유럽' },
  { term: 'pl 폴란드 poland', flag: '🇵🇱', name: '폴란드', continent: '유럽' },
  { term: 'cz 체코 czech republic czechia', flag: '🇨🇿', name: '체코', continent: '유럽' },
  { term: 'sk 슬로바키아 slovakia', flag: '🇸🇰', name: '슬로바키아', continent: '유럽' },
  { term: 'hu 헝가리 hungary', flag: '🇭🇺', name: '헝가리', continent: '유럽' },
  { term: 'ro 루마니아 romania', flag: '🇷🇴', name: '루마니아', continent: '유럽' },
  { term: 'bg 불가리아 bulgaria', flag: '🇧🇬', name: '불가리아', continent: '유럽' },
  { term: 'gr 그리스 greece', flag: '🇬🇷', name: '그리스', continent: '유럽' },
  { term: 'hr 크로아티아 croatia', flag: '🇭🇷', name: '크로아티아', continent: '유럽' },
  { term: 'si 슬로베니아 slovenia', flag: '🇸🇮', name: '슬로베니아', continent: '유럽' },
  { term: 'rs 세르비아 serbia', flag: '🇷🇸', name: '세르비아', continent: '유럽' },
  { term: 'ba 보스니아 헤르체고비나 bosnia herzegovina', flag: '🇧🇦', name: '보스니아 헤르체고비나', continent: '유럽' },
  { term: 'me 몬테네그로 montenegro', flag: '🇲🇪', name: '몬테네그로', continent: '유럽' },
  { term: 'mk 북마케도니아 north macedonia', flag: '🇲🇰', name: '북마케도니아', continent: '유럽' },
  { term: 'al 알바니아 albania', flag: '🇦🇱', name: '알바니아', continent: '유럽' },
  { term: 'xk 코소보 kosovo', flag: '🇽🇰', name: '코소보', continent: '유럽' },
  { term: 'ru 러시아 russia', flag: '🇷🇺', name: '러시아', continent: '유럽' },
  { term: 'ua 우크라이나 ukraine', flag: '🇺🇦', name: '우크라이나', continent: '유럽' },
  { term: 'by 벨라루스 belarus', flag: '🇧🇾', name: '벨라루스', continent: '유럽' },
  { term: 'md 몰도바 moldova', flag: '🇲🇩', name: '몰도바', continent: '유럽' },
  { term: 'ee 에스토니아 estonia', flag: '🇪🇪', name: '에스토니아', continent: '유럽' },
  { term: 'lv 라트비아 latvia', flag: '🇱🇻', name: '라트비아', continent: '유럽' },
  { term: 'lt 리투아니아 lithuania', flag: '🇱🇹', name: '리투아니아', continent: '유럽' },
  { term: 'lu 룩셈부르크 luxembourg', flag: '🇱🇺', name: '룩셈부르크', continent: '유럽' },
  { term: 'mc 모나코 monaco', flag: '🇲🇨', name: '모나코', continent: '유럽' },
  { term: 'ad 안도라 andorra', flag: '🇦🇩', name: '안도라', continent: '유럽' },
  { term: 'li 리히텐슈타인 liechtenstein', flag: '🇱🇮', name: '리히텐슈타인', continent: '유럽' },
  { term: 'sm 산마리노 san marino', flag: '🇸🇲', name: '산마리노', continent: '유럽' },
  { term: 'va 바티칸 vatican', flag: '🇻🇦', name: '바티칸', continent: '유럽' },
  { term: 'mt 몰타 malta', flag: '🇲🇹', name: '몰타', continent: '유럽' },
  { term: 'us 미국 usa united states', flag: '🇺🇸', name: '미국', continent: '북아메리카' },
  { term: 'ca 캐나다 canada', flag: '🇨🇦', name: '캐나다', continent: '북아메리카' },
  { term: 'mx 멕시코 mexico', flag: '🇲🇽', name: '멕시코', continent: '북아메리카' },
  { term: 'gt 과테말라 guatemala', flag: '🇬🇹', name: '과테말라', continent: '북아메리카' },
  { term: 'bz 벨리즈 belize', flag: '🇧🇿', name: '벨리즈', continent: '북아메리카' },
  { term: 'hn 온두라스 honduras', flag: '🇭🇳', name: '온두라스', continent: '북아메리카' },
  { term: 'sv 엘살바도르 el salvador', flag: '🇸🇻', name: '엘살바도르', continent: '북아메리카' },
  { term: 'ni 니카라과 nicaragua', flag: '🇳🇮', name: '니카라과', continent: '북아메리카' },
  { term: 'cr 코스타리카 costa rica', flag: '🇨🇷', name: '코스타리카', continent: '북아메리카' },
  { term: 'pa 파나마 panama', flag: '🇵🇦', name: '파나마', continent: '북아메리카' },
  { term: 'cu 쿠바 cuba', flag: '🇨🇺', name: '쿠바', continent: '북아메리카' },
  { term: 'jm 자메이카 jamaica', flag: '🇯🇲', name: '자메이카', continent: '북아메리카' },
  { term: 'ht 아이티 haiti', flag: '🇭🇹', name: '아이티', continent: '북아메리카' },
  { term: 'do 도미니카공화국 dominican republic', flag: '🇩🇴', name: '도미니카공화국', continent: '북아메리카' },
  { term: 'tt 트리니다드 토바고 trinidad tobago', flag: '🇹🇹', name: '트리니다드 토바고', continent: '북아메리카' },
  { term: 'bs 바하마 bahamas', flag: '🇧🇸', name: '바하마', continent: '북아메리카' },
  { term: 'bb 바베이도스 barbados', flag: '🇧🇧', name: '바베이도스', continent: '북아메리카' },
  { term: 'gd 그레나다 grenada', flag: '🇬🇩', name: '그레나다', continent: '북아메리카' },
  { term: 'lc 세인트루시아 saint lucia', flag: '🇱🇨', name: '세인트루시아', continent: '북아메리카' },
  { term: 'vc 세인트빈센트 그레나딘 saint vincent grenadines', flag: '🇻🇨', name: '세인트빈센트 그레나딘', continent: '북아메리카' },
  { term: 'ag 앤티가 바부다 antigua barbuda', flag: '🇦🇬', name: '앤티가 바부다', continent: '북아메리카' },
  { term: 'kn 세인트키츠 네비스 saint kitts nevis', flag: '🇰🇳', name: '세인트키츠 네비스', continent: '북아메리카' },
  { term: 'dm 도미니카 dominica', flag: '🇩🇲', name: '도미니카', continent: '북아메리카' },
  { term: 'br 브라질 brazil', flag: '🇧🇷', name: '브라질', continent: '남아메리카' },
  { term: 'ar 아르헨티나 argentina', flag: '🇦🇷', name: '아르헨티나', continent: '남아메리카' },
  { term: 'cl 칠레 chile', flag: '🇨🇱', name: '칠레', continent: '남아메리카' },
  { term: 'co 콜롬비아 colombia', flag: '🇨🇴', name: '콜롬비아', continent: '남아메리카' },
  { term: 'pe 페루 peru', flag: '🇵🇪', name: '페루', continent: '남아메리카' },
  { term: 'ec 에콰도르 ecuador', flag: '🇪🇨', name: '에콰도르', continent: '남아메리카' },
  { term: 'bo 볼리비아 bolivia', flag: '🇧🇴', name: '볼리비아', continent: '남아메리카' },
  { term: 'py 파라과이 paraguay', flag: '🇵🇾', name: '파라과이', continent: '남아메리카' },
  { term: 'uy 우루과이 uruguay', flag: '🇺🇾', name: '우루과이', continent: '남아메리카' },
  { term: 've 베네수엘라 venezuela', flag: '🇻🇪', name: '베네수엘라', continent: '남아메리카' },
  { term: 'gy 가이아나 guyana', flag: '🇬🇾', name: '가이아나', continent: '남아메리카' },
  { term: 'sr 수리남 suriname', flag: '🇸🇷', name: '수리남', continent: '남아메리카' },
  { term: 'eg 이집트 egypt', flag: '🇪🇬', name: '이집트', continent: '아프리카' },
  { term: 'ma 모로코 morocco', flag: '🇲🇦', name: '모로코', continent: '아프리카' },
  { term: 'tn 튀니지 tunisia', flag: '🇹🇳', name: '튀니지', continent: '아프리카' },
  { term: 'dz 알제리 algeria', flag: '🇩🇿', name: '알제리', continent: '아프리카' },
  { term: 'ly 리비아 libya', flag: '🇱🇾', name: '리비아', continent: '아프리카' },
  { term: 'sd 수단 sudan', flag: '🇸🇩', name: '수단', continent: '아프리카' },
  { term: 'ss 남수단 south sudan', flag: '🇸🇸', name: '남수단', continent: '아프리카' },
  { term: 'et 에티오피아 ethiopia', flag: '🇪🇹', name: '에티오피아', continent: '아프리카' },
  { term: 'er 에리트레아 eritrea', flag: '🇪🇷', name: '에리트레아', continent: '아프리카' },
  { term: 'dj 지부티 djibouti', flag: '🇩🇯', name: '지부티', continent: '아프리카' },
  { term: 'so 소말리아 somalia', flag: '🇸🇴', name: '소말리아', continent: '아프리카' },
  { term: 'ke 케냐 kenya', flag: '🇰🇪', name: '케냐', continent: '아프리카' },
  { term: 'tz 탄자니아 tanzania', flag: '🇹🇿', name: '탄자니아', continent: '아프리카' },
  { term: 'ug 우간다 uganda', flag: '🇺🇬', name: '우간다', continent: '아프리카' },
  { term: 'rw 르완다 rwanda', flag: '🇷🇼', name: '르완다', continent: '아프리카' },
  { term: 'bi 부룬디 burundi', flag: '🇧🇮', name: '부룬디', continent: '아프리카' },
  { term: 'za 남아프리카공화국 south africa', flag: '🇿🇦', name: '남아프리카공화국', continent: '아프리카' },
  { term: 'ng 나이지리아 nigeria', flag: '🇳🇬', name: '나이지리아', continent: '아프리카' },
  { term: 'gh 가나 ghana', flag: '🇬🇭', name: '가나', continent: '아프리카' },
  { term: 'sn 세네갈 senegal', flag: '🇸🇳', name: '세네갈', continent: '아프리카' },
  { term: 'ci 코트디부아르 ivory coast cote divoire', flag: '🇨🇮', name: '코트디부아르', continent: '아프리카' },
  { term: 'cm 카메룬 cameroon', flag: '🇨🇲', name: '카메룬', continent: '아프리카' },
  { term: 'ao 앙골라 angola', flag: '🇦🇴', name: '앙골라', continent: '아프리카' },
  { term: 'mz 모잠비크 mozambique', flag: '🇲🇿', name: '모잠비크', continent: '아프리카' },
  { term: 'zw 짐바브웨 zimbabwe', flag: '🇿🇼', name: '짐바브웨', continent: '아프리카' },
  { term: 'zm 잠비아 zambia', flag: '🇿🇲', name: '잠비아', continent: '아프리카' },
  { term: 'mw 말라위 malawi', flag: '🇲🇼', name: '말라위', continent: '아프리카' },
  { term: 'mg 마다가스카르 madagascar', flag: '🇲🇬', name: '마다가스카르', continent: '아프리카' },
  { term: 'mu 모리셔스 mauritius', flag: '🇲🇺', name: '모리셔스', continent: '아프리카' },
  { term: 'sc 세이셸 seychelles', flag: '🇸🇨', name: '세이셸', continent: '아프리카' },
  { term: 'km 코모로 comoros', flag: '🇰🇲', name: '코모로', continent: '아프리카' },
  { term: 'cf 중앙아프리카공화국 central african republic', flag: '🇨🇫', name: '중앙아프리카공화국', continent: '아프리카' },
  { term: 'cg 콩고 congo', flag: '🇨🇬', name: '콩고', continent: '아프리카' },
  { term: 'cd 콩고민주공화국 democratic republic of the congo drc', flag: '🇨🇩', name: '콩고민주공화국', continent: '아프리카' },
  { term: 'ga 가봉 gabon', flag: '🇬🇦', name: '가봉', continent: '아프리카' },
  { term: 'gq 적도기니 equatorial guinea', flag: '🇬🇶', name: '적도기니', continent: '아프리카' },
  { term: 'st 상투메 프린시페 sao tome principe', flag: '🇸🇹', name: '상투메 프린시페', continent: '아프리카' },
  { term: 'cv 카보베르데 cape verde', flag: '🇨🇻', name: '카보베르데', continent: '아프리카' },
  { term: 'gw 기니비사우 guinea-bissau', flag: '🇬🇼', name: '기니비사우', continent: '아프리카' },
  { term: 'gn 기니 guinea', flag: '🇬🇳', name: '기니', continent: '아프리카' },
  { term: 'sl 시에라리온 sierra leone', flag: '🇸🇱', name: '시에라리온', continent: '아프리카' },
  { term: 'lr 라이베리아 liberia', flag: '🇱🇷', name: '라이베리아', continent: '아프리카' },
  { term: 'tg 토고 togo', flag: '🇹🇬', name: '토고', continent: '아프리카' },
  { term: 'bj 베냉 benin', flag: '🇧🇯', name: '베냉', continent: '아프리카' },
  { term: 'bf 부르키나파소 burkina faso', flag: '🇧🇫', name: '부르키나파소', continent: '아프리카' },
  { term: 'ml 말리 mali', flag: '🇲🇱', name: '말리', continent: '아프리카' },
  { term: 'ne 니제르 niger', flag: '🇳🇪', name: '니제르', continent: '아프리카' },
  { term: 'td 차드 chad', flag: '🇹🇩', name: '차드', continent: '아프리카' },
  { term: 'mr 모리타니 mauritania', flag: '🇲🇷', name: '모리타니', continent: '아프리카' },
  { term: 'gm 감비아 gambia', flag: '🇬🇲', name: '감비아', continent: '아프리카' },
  { term: 'na 나미비아 namibia', flag: '🇳🇦', name: '나미비아', continent: '아프리카' },
  { term: 'bw 보츠와나 botswana', flag: '🇧🇼', name: '보츠와나', continent: '아프리카' },
  { term: 'ls 레소토 lesotho', flag: '🇱🇸', name: '레소토', continent: '아프리카' },
  { term: 'sz 에스와티니 eswatini swaziland', flag: '🇸🇿', name: '에스와티니', continent: '아프리카' },
  { term: 'au 호주 australia', flag: '🇦🇺', name: '호주', continent: '오세아니아' },
  { term: 'nz 뉴질랜드 new zealand', flag: '🇳🇿', name: '뉴질랜드', continent: '오세아니아' },
  { term: 'pg 파푸아뉴기니 papua new guinea', flag: '🇵🇬', name: '파푸아뉴기니', continent: '오세아니아' },
  { term: 'fj 피지 fiji', flag: '🇫🇯', name: '피지', continent: '오세아니아' },
  { term: 'sb 솔로몬제도 solomon islands', flag: '🇸🇧', name: '솔로몬제도', continent: '오세아니아' },
  { term: 'vu 바누아투 vanuatu', flag: '🇻🇺', name: '바누아투', continent: '오세아니아' },
  { term: 'ws 사모아 samoa', flag: '🇼🇸', name: '사모아', continent: '오세아니아' },
  { term: 'to 통가 tonga', flag: '🇹🇴', name: '통가', continent: '오세아니아' },
  { term: 'fm 미크로네시아 micronesia', flag: '🇫🇲', name: '미크로네시아', continent: '오세아니아' },
  { term: 'pw 팔라우 palau', flag: '🇵🇼', name: '팔라우', continent: '오세아니아' },
  { term: 'mh 마셜제도 marshall islands', flag: '🇲🇭', name: '마셜제도', continent: '오세아니아' },
  { term: 'ki 키리바시 kiribati', flag: '🇰🇮', name: '키리바시', continent: '오세아니아' },
  { term: 'tv 투발루 tuvalu', flag: '🇹🇻', name: '투발루', continent: '오세아니아' },
  { term: 'nr 나우루 nauru', flag: '🇳🇷', name: '나우루', continent: '오세아니아' },
];

// ─── 국가 한글명 → 영어 표기 (블로그 카드 등 영문 라벨용) ───
// term은 "코드 한글명 영문명 [검색 별칭...]" 형태 — 별칭이 섞인 국가는 예외 표로 정확한 표기를 지정
const EN_NAME_OVERRIDES: Record<string, string> = {
  mm: 'Myanmar',
  tl: 'East Timor',
  ae: 'United Arab Emirates',
  tr: 'Turkey',
  gb: 'United Kingdom',
  cz: 'Czech Republic',
  us: 'United States',
  ci: 'Ivory Coast',
  cd: 'DR Congo',
  sz: 'Eswatini',
};
export const countryEnglishName = (koreanName?: string): string => {
  if (!koreanName) return '';
  const c = COUNTRIES.find((x) => x.name === koreanName);
  if (!c) return koreanName;
  const tokens = c.term.split(' ');
  const override = EN_NAME_OVERRIDES[tokens[0]];
  if (override) return override;
  const ascii = tokens.slice(1).filter((w) => /^[a-z()\-']+$/i.test(w));
  const en = ascii.join(' ').replace(/(^|\s)[a-z]/g, (m) => m.toUpperCase());
  return en || koreanName;
};
